### ISSUE TITLE
Market data sharing of concurrent live and paper sessions

### ISSUE THREAD

**Issue by handelsmeisterei** [extrange/ibkr-docker#102]
I have a problem with ibkr-docker which I cannot wrap my head around:

IB allows sharing of market data between live and paper trading accounts as long as both TWS/Gateway run on the same machine. This unfortunately does not work when using docker, because each container counts as a different machine for IB.

As I have a live trading container that I do not want to stop while I am testing some new stuff in paper trading, this is a severe problem for me. Are there any ideas how I could run two TWS instances from within one container or other solutions?

**Comment by extrange** [comment]
This has been discussed previously in #64, and unfortunately I don't have the bandwidth to write the solution at present.
