### ISSUE TITLE
Gateway shows as GreyBox

### ISSUE THREAD

**Issue by pjsteele** [extrange/ibkr-docker#24]
I am seeing a Grey Box when using the console. This appears after I login, before that VNC shows everything as expected.

Am I doing something wrong? 

```docker run -d -p "127.0.0.1:6080:6080" -p "127.0.0.1:8888:8888" --ulimit nofile=10000 -e USERNAME=XXXX -e PASSWORD=PXXX -e GATEWAY_OR_TWS=gateway ghcr.io/extrange/ibkr:latest```

![image](https://user-images.githubusercontent.com/6556324/235641601-a6bdbe27-84eb-4238-a411-d51afde80d97.png)

**Comment by extrange** [comment]
The grey 'box' can be dragged away, and it will show the UI underneath. I'm not sure what the cause is as of yet.

**Comment by pjsteele** [comment]
Thanks! That worked for me
