### ISSUE TITLE
Read file config blocked

### ISSUE THREAD

**Issue by perriea** [extrange/ibkr-docker#3]
Hi !

Thanks for your work !
I get stuck on this screen : 
![Capture d’écran 2022-01-08 à 15 51 48](https://user-images.githubusercontent.com/15982613/148648969-07738e8e-ad79-4233-92a9-69bbd85aadff.png)

I am not sure that this is the image that is the source of this problem, however I had these issues locally and on my Kubernetes cluster.
Furthermore, I can't find any specific logs to this issue ...

My config (basic):
```ini
FIX=no
IbLoginId=XXXXXX
IbPassword=XXXX
FIXLoginId=
FIXPassword=
ExitAfterSecondFactorAuthenticationTimeout=no
SecondFactorAuthenticationExitInterval=
TradingMode=paper
AcceptNonBrokerageAccountWarning=yes
LoginDialogDisplayTimeout = 60
IbDir=
StoreSettingsOnServer=
MinimizeMainWindow=no
ExistingSessionDetectedAction=manual
OverrideTwsApiPort=
ReadOnlyLogin=no
ReadOnlyApi=no
AcceptBidAskLastSizeDisplayUpdateNotification=accept
SendMarketDataInLotsForUSstocks=
IbAutoClosedown=yes
ClosedownAt=
AcceptIncomingConnectionAction=accept
AllowBlindTrading=no
SaveTwsSettingsAt=
DismissPasswordExpiryWarning=no
DismissNSEComplianceNotice=yes
ControlFrom=
BindAddress=
CommandPrompt=
SuppressInfoMessages=yes
LogStructureScope=known
LogStructureWhen=never
```

Has anyone ever had this?

**Comment by perriea** [comment]
I had this problem in TWS or Gateway mode

**Comment by perriea** [comment]
After finding and changing Dockerfile (rootless), my problem is solved. I think rights were not correct. 
https://github.com/arktos-venture/docker-ibkr/tree/develop/app/gateway

**Comment by extrange** [comment]
Saw you added a new user `trader` in your [`Dockerfile`](https://github.com/arktos-venture/docker-ibkr/blob/6c9e118467a3b848b056f0eaea5e9f0c249bb6ef/app/gateway/Dockerfile#L34) - this could be the problem. Looks like you managed to fix the permissions with `chown` so I'm closing this!
