### ISSUE TITLE
VNC client

### ISSUE THREAD

**Issue by oldirtybasti** [extrange/ibkr-docker#31]
Thanks for that very interesting image! 

Is it possible to have vnc without browser access via an vnc client supported? 

I find it cumbersome to have a different url each time and also could not get it working accessing from my local machine via wireguard to the cloud provider.

**Comment by oldirtybasti** [comment]
oh I just realized that it is possible to just connect by a static adrdess, just edit the url:

http://IPADRESS:6080/vnc.html?host=IPADRESS&port=6080

**Comment by extrange** [comment]
Yes, you can use VNC also, but you'll have to open that port manually on the image. noVNC should work with any device with a browser, and the url should not be changing each time.
