### ISSUE TITLE
Latest docker image should be TWS version 10.23.2a

### ISSUE THREAD

**Issue by oldirtybasti** [extrange/ibkr-docker#33]
Unfortunately the stable version currently does not work for me. I get an error "Download of settings failed". With the latest docker image 10.23.1q everything works fine.

Unfortunately this is not the latest version, I now get the following message:
<img width="926" alt="Screenshot 2023-07-07 at 08 40 04 1" src="https://github.com/extrange/ibkr-docker/assets/2550869/59050b22-6b5f-44a8-8971-3a19e86d4de3">

Is it possible to create a new image version which contains 10.23.2a? There already is a pull request for that version, but I cannot find the respective docker image on
https://github.com/extrange/ibkr-docker/pkgs/container/ibkr/versions?filters%5Bversion_type%5D=tagged

**Comment by oldirtybasti** [comment]
As a note for other users: With local settings (not stored on server), the current stable version works fine.

**Comment by extrange** [comment]
The pull requests are automated, the actual docker image creation and pushing is performed when I push the respective tag. I'll have a look at this, thanks for bringing it up.

**Comment by extrange** [comment]
Updated `latest` to 10.23.2a and `stable` to 10.19.2a
