### ISSUE TITLE
Container doesn't work on aarch64 machine

### ISSUE THREAD

**Issue by nimrodhagay** [extrange/ibkr-docker#36]
Trying to run the container on arm machine returns an error :
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

**Comment by extrange** [comment]
Unfortunately, the images work only on x86 architectures for now. Part of the difficulty is the JRE supplied with IB, which hasn't been [ported properly to ARM](https://trenki2.github.io/blog/2018/01/04/trading-with-raspberry-pi/).
