### ISSUE TITLE
no paper connection possible

### ISSUE THREAD

**Issue by JustinGuese** [extrange/ibkr-docker#47]
```
2023/09/04 17:20:32 socat[149] N opening connection to AF=2 127.0.0.1:7497
2023/09/04 17:20:32 socat[149] W recvmsg(): Resource temporarily unavailable
2023/09/04 17:20:32 socat[149] E connect(5, AF=2 127.0.0.1:7497, 16): Connection refused
2023/09/04 17:20:32 socat[149] N exit(1)
```

connecting via VPC looks like it's not being able to click the login button

using :stable
tried gateway and tws

**Comment by JustinGuese** [comment]
Hi!
I can't for security reasons, but it is (in both tws and gateway) the login mask of the paper trade... so my user and password is filled in, but nothing happens. logs only show the above message.

I have pulled the stable image yesterday, so I guess I have the same version number?

I am using paper

Any tips what could be going wrong? I'll try the same on a new hetzner VM to check if it has to do with my ip or server

**Comment by extrange** [comment]
Did you set `IBC_TradingMode=paper` in docker compose?

**Comment by JustinGuese** [comment]
good news, my password contained "$" so I guess something pasted... but changing the password to a non "$" version works! thanks for your help!
