### ISSUE TITLE
Cannot connect to TWS/ IB Gateway on GCP

### ISSUE THREAD

**Issue by MarioMZhang** [extrange/ibkr-docker#52]
Hi there,

I'm working on google cloud and got this error when connecting
![image](https://github.com/extrange/ibkr-docker/assets/52642523/ca7956e3-0234-4eb6-b627-d94f41d7f591)
![image](https://github.com/extrange/ibkr-docker/assets/52642523/0e3e5ebb-5685-4d21-9321-f1e6e5202cfe)
I had the global configuration set on `localhost:6080`
![image](https://github.com/extrange/ibkr-docker/assets/52642523/964987d8-42e6-4c8a-9520-13f7c59e8663)

from the docker's log, i feel like I can connect to the API port 
![image](https://github.com/extrange/ibkr-docker/assets/52642523/d6302e92-ab64-428d-be82-d5fd7eabe1db)
there is no connection refused log as in #16 

Could anyone help? Thanks in advance!

**Comment by extrange** [comment]
Have you forwarded the ports in `docker-compose.yml`?

**Comment by MarioMZhang** [comment]
> Have you forwarded the ports in `docker-compose.yml`?

Thanks for the reply!
I don't think so, do we have a pointer to forward ports? 
here is my `compose.yml`
<img width="508" alt="image" src="https://github.com/extrange/ibkr-docker/assets/52642523/9a1ad137-6fa5-42b8-916e-f18bfed3954d">

**Comment by MarioMZhang** [comment]
> Have you forwarded the ports in `docker-compose.yml`?

are we supposed to use app.connect('127.0.0.1',8888,xxx). I feel like I misunderstood the readme

**Comment by MarioMZhang** [comment]
Hi @extrange ,
after changing the port to 8888, I was able to connect, but not sure if it's the right way to do so. if so, how do I know if I'm on live or paper mode?  Thanks!

**Comment by extrange** [comment]
That's correct, port `8888` is where the TWS API is [being exposed](https://github.com/extrange/ibkr-docker#using-docker-compose-recommended).

You can set the mode with the variable [IBC_TradingMode](https://github.com/extrange/ibkr-docker#environment-variables) (default `live`).
