### ISSUE TITLE
remove Client 1 , can't connect.

### ISSUE THREAD

**Issue by thunderwin** [extrange/ibkr-docker#55]
I m using docker-compose,, 

docker running well. 

but when I try to connect,  says  "remove Client"

here is the logs,

 starting data transfer loop with FDs [6,6] and [5,5]
remove Client 0
2023/10/05 11:22:15 socat[236] N socket 1 (fd 6) is at EOF
2023/10/05 11:22:15 socat[236] N socket 2 (fd 5) is at EOF
2023/10/05 11:22:15 socat[236] N exiting with status 0
2023/10/05 11:22:15 socat[11] N childdied(): handling signal 17
2023/10/05 11:22:35 socat[11] N accepting connection from AF=2 159.138.57.90:50374 on AF=2 192.168.48.2:8888
2023/10/05 11:22:35 socat[11] N forked off child process 242
2023/10/05 11:22:35 socat[11] N listening on AF=2 0.0.0.0:8888
2023/10/05 11:22:35 socat[242] N opening connection to AF=2 127.0.0.1:4001
2023/10/05 11:22:35 socat[242] N successfully connected from local address AF=2 127.0.0.1:51850
2023/10/05 11:22:35 socat[242] N starting data transfer loop with FDs [6,6] and [5,5]
remove Client 23

and I have checked the logs in the web interface:
shows there is a connection, but there is no response keep hanging on me.

<img width="748" alt="image" src="https://github.com/extrange/ibkr-docker/assets/2757750/a4a4c9c8-a189-4618-8926-45411cef9914">

API looks all right, just no response. keep hanging :

 app = TestApp()
    app.connect("xxxxxx", 8888, 23)
    app.run()
    orders = app.reqPositions()
    print(orders)

**Comment by extrange** [comment]
What library are you using to connect? Did you expose the ports?

**Comment by thunderwin** [comment]
ok my bad.  my client issue.  I just switched to ib_insync, and solved!
